---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: test-ci-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/faust64/tekton-demo.git
  - name: revision
    value: 151d066ee4cdfa1eabb527d09e2e112317de7acf
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: test-ci-temp-image
spec:
  type: image
  params:
  - name: url
    value: registry.registry.svc.cluster.local:5000/test-tekton/tekton-demo:151d066ee4cdfa1eabb527d09e2e112317de7acf
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: test-ci-target-image
spec:
  type: image
  params:
  - name: url
    value: registry.registry.svc.cluster.local:5000/test-tekton/tekton-demo:master
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-pipeline-
spec:
  params:
  - name: identifier
    value: demo-151d066ee4cdfa1eabb527d09e2e112317de7acf
  - name: cins
    value: test-tekton
  pipelineRef:
    name: ci-docker-build
  resources:
  - name: app-git
    resourceRef:
      name: test-ci-repo
  - name: ci-image
    resourceRef:
      name: test-ci-temp-image
  - name: target-image
    resourceRef:
      name: test-ci-target-image
  serviceAccountName: test-tkn
  timeout: 2h0m0s
#  timeouts:
#    pipeline: 2h0m0s
  workspaces:
  - name: sigsecret
    secret:
      secretName: tekton-cosign-private
