# WARNING: the secret below is a dummy value, which could be suitable
# testing those pipelines. Generate your own key pair with ASAP:
# => cosign generate-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-cosign-private
stringData:
  cosign.key: |
    -----BEGIN ENCRYPTED COSIGN PRIVATE KEY-----
    eyJrZGYiOnsibmFtZSI6InNjcnlwdCIsInBhcmFtcyI6eyJOIjozMjc2OCwiciI6
    OCwicCI6MX0sInNhbHQiOiJJVzNBcG9ucHVOK09VM2QrVzNaM0VMbkx6aUFybHVF
    STVaa0NIVFNzQUt3PSJ9LCJjaXBoZXIiOnsibmFtZSI6Im5hY2wvc2VjcmV0Ym94
    Iiwibm9uY2UiOiJYOEIzOTdKSnkvREE0YVdpbFBZclBtakhCVnBZZEV6QyJ9LCJj
    aXBoZXJ0ZXh0IjoiSXM0M05JSjZCMmFMdjBMQitOMGV2OVBKVEczdGNCUWxBRU5P
    VlVNbG85WWw0UlVFbEZCYUhONGhLQm1uZWlyZmZIQXNpYmF5RDNpd01YRWFEUjNs
    dHVLK3NsU3dkaGlldzMySGwrQmpOakp3ZmV1UGJyQlZ1UGZIaWpUSFpHRDdvVG9m
    aGRiYjZBNUltNERXZGxobzlWMWFkMEE1YnBlUTVtUkVxSVRKNmxEeDJXVzZMTXBH
    MzB4TUpXdXJsNzZEM3ZPRE1wSzhESnBBWnc9PSJ9
    -----END ENCRYPTED COSIGN PRIVATE KEY-----
  passphrase: secret
---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-cosign-public
stringData:
  cosign.pub: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEI4eusCpjXxSWxkU8jtb2ePmgsd3X
    9rYLU+URaACp6WAjuiCJx9RZ7iNtjO0disavksiEQEa8PqImM11CXRC5hg==
    -----END PUBLIC KEY-----
