---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      name: NAME_PLACEHOLDER
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: NAME_PLACEHOLDER
    spec:
      containers:
      - image: IMAGE_PLACEHOLDER
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 8080
        name: demo
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: NAME_PLACEHOLDER
spec:
  ports:
  - name: http
    port: 8080
  selector:
    name: NAME_PLACEHOLDER
